- name: Hello World Sample
  hosts: all
  vars_prompt:
  - name: codename
    prompt: "Pleasse enter a UNIQUE codename."
    
  tasks:
    - name: Create Workspace
      file:
        path: /root/{{ codename }}
        state: directory

