- name: Hello World Sample
  hosts: all
  gather_facts: no
    
  tasks:
    - name: Download Kolide Scripts
      git:
        repo: 'https://github.com/Epod/awx-kolide.git'
        dest: /opt//kolide/{{ codename }}

