- name: Hello World Sample
  hosts: all
  vars_prompt:
  - name: codename
    prompt: "Pleasse enter a UNIQUE codename."
    
  tasks:
    - name: Create Workspace
      debug:
        msg: "Creating workspace in /root/{{ codename }}"
      file:
        path: /root/{{ codename }}
        state: directory

