- name: Delete Kolide Fleet
  hosts: all
  gather_facts: no

  tasks:
    
    - name: Shutting Down Kolide Instance
      docker_compose:
        project_src: /opt/kolide/{{ codename }}
        state : absent
        remove_volumes: yes

    - name: Remove All Customer Data
      shell: rm -rf /opt/kolide/{{ codename }}
      args:
        warn: no
